### ISSUE TITLE
The simulated polar Eta are always falling

### ISSUE THREAD

**Issue by liu-ran** [MITgcm-contrib/ecco_darwin#1]
The simulated polar Eta are always falling when I use the physical component ( only gfd and seaice packages ) of the llc270 configuration. The forcing data is COREv2. The initial data is the same as the llc270 configuration. After 40 years' simulation, the minimum Eta can reach -18 meters in the Arctic sea as shown in the following figure. But the U is still normal. Do we have to enable the CTRL package for the llc270?
![微信图片_20200917122203](https://user-images.githubusercontent.com/48266323/93419864-7951fb00-f8e0-11ea-96be-d956bbcdc43b.png)

**Comment by menemenlis** [comment]
To get dynamic sea level, you need to add HEFF and HSNOW multiplied by their respective densities.
The low Eta just means that you are growing sea ice.

The forcing provided in MITgcm-contrib/ecco_darwin is adjusted to fit observations using the adjoint method.
Any other forcing would almost certainly require some readjustments in order to avoid model drift.

**Comment by liu-ran** [comment]
Yes, my STDOUT.0000 file shows that the mean ice thickness did increase. And finally, the low Eta leads to the model stop because " r*FacW < hFacInf " as the picture shows. Is there any advice or experience if someone wants to test the sensitivity of ocean circulation to different forcing using the llc270 configuration? 
![微信图片_20200917153129](https://user-images.githubusercontent.com/48266323/93435440-0ce4f500-f8fc-11ea-85a4-1a727f6cda62.png)

**Comment by menemenlis** [comment]
What you are doing is fine.  We carry out this type of sensitivity experiments all the time.
The reason that the model fails in your case is that the sea ice pushes down on sea level and eventually
the model runs out of water at that grid cell — the threshold of required minimum water being set by hFacInf variable.

Recompile with "#define SEAICE_CAP_ICELOAD” in SEAICE_OPTIONS.h
This will allow the model to continue running even when your configuration creates very thick sea ice.

**Comment by liu-ran** [comment]
Many thanks! 

> What you are doing is fine.  We carry out this type of sensitivity experiments all the time.
> The reason that the model fails in your case is that the sea ice pushes down on sea level and eventually
> the model runs out of water at that grid cell — the threshold of required minimum water being set by hFacInf variable.
> 
> Recompile with "#define SEAICE_CAP_ICELOAD” in SEAICE_OPTIONS.h
> This will allow the model to continue running even when your configuration creates very thick sea ice.
> …
