### ISSUE TITLE
ecco darwin climatology benchmark

### ISSUE THREAD

**Issue by liu-ran** [MITgcm-contrib/ecco_darwin#13]
Hi every great master,

Would you mind packaging the climatological physical and biochemical data for the llc270 Darwin simulation as a standard MITgcm verification so that downstream researchers can run llc270 Darwin to test some dynamical responses or other details? Thank you very much!

Best,
Ran

**Comment by menemenlis** [comment]
Hi Ran, just saw this.  The input files are too big to package llc270 as a verification experiment.  However, there are instructions under the readme.txt and how to obtain input files from other sources. Some 3-degree experiments are fully checked in git.

**Comment by menemenlis** [comment]
This probably has been answered already, but just in case:
https://github.com/MITgcm-contrib/ecco_darwin/tree/master/v05/llc270
