### ISSUE TITLE
Question about using ecco_darwin for adjoint sensitivity studies

### ISSUE THREAD

**Issue by DanJonesOcean** [MITgcm-contrib/ecco_darwin#7]
Hi all,

Thanks so much for sharing ecco_darwin. I have a question about using ecco_darwin for adjoint sensitivity studies, e.g. using the ECCO framework. Is that possible? If so, are there configurations in this repository that you all would recommend starting with? 

Thanks in advance for any guidance/clarification you can provide.

**Comment by menemenlis** [comment]
Hi Dan, we have not yet used any of the configurations checked-in here:
https://github.com/MITgcm-contrib/ecco_darwin <https://github.com/MITgcm-contrib/ecco_darwin>
for adjoint sensitivity studies.

pkg/bling and pkg/dic have previously been used for adjoint sensitivity studies.

D.

**Comment by DanJonesOcean** [comment]
Thanks for your quick reply, @menemenlis. 

Apologies if I'm missing something - I suspect the answer is right in front of me, but I'm not seeing it - how is the cost function calculated in these configurations? I don't see the `ecco` package or the `cost` package in `packages.conf` or any of the input files. I'm looking here, for example: 

[https://github.com/MITgcm-contrib/ecco_darwin/tree/master/v05/llc270](https://github.com/MITgcm-contrib/ecco_darwin/tree/master/v05/llc270)

I do see the `ctrl` package, which makes sense. I'm just used to also seeing `ecco` or `cost` along with it. Are these forward-only setups?

**Comment by menemenlis** [comment]
Hi Dan, yes, these are forward-only setups.
The ECCO-Darwin set-ups have never been used for adjoint computations.

pkg/dic
https://mitgcm.readthedocs.io/en/latest/phys_pkgs/dic.html?highlight=dic <https://mitgcm.readthedocs.io/en/latest/phys_pkgs/dic.html?highlight=dic>
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2002JC001598

and pkg/bling
https://github.com/MITgcm/MITgcm/tree/master/pkg/bling <https://github.com/MITgcm/MITgcm/tree/master/pkg/bling>
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016JC012650

Dimitris

**Comment by DanJonesOcean** [comment]
@menemenlis Ah okay, I see now that ECCO-Darwin uses a Green's function approach to adjust the biogeochemistry. I should have read the paper a little more carefully. Thanks.  : )
