### ISSUE TITLE
Long-term mean data available for ECCO-Darwin?

### ISSUE THREAD

**Issue by DanJonesOcean** [MITgcm-contrib/ecco_darwin#9]
Hiya - I am interested in plotting the long-term mean CO2 flux in ECCO-Darwin, using different units and a different scale. I see that the monthly mean data is available via the NASA ECCO Data Portal, but I don't think I have time to download all the months at present. Are there plans to make this data accessible via Pangeo or a similar platform? Ideally, I would also like the time-integrated fluxes at each grid cell. Thanks in advance for any help/guidance you can provide.

**Comment by menemenlis** [comment]
Hi Dan, yes to your first question.  The ECCO-Darwin model output will (eventually) be made available via Pangeo or other similar platforms.  Technically it already is since there are Pangeo tools for accessing the NASA ECCO Data Portal.

By time integrated fluxes, do you mean surface CO2 fluxes, as done here: https://doi.org/10.1029/2019MS001888 <https://doi.org/10.1029/2019MS001888>
or full-depth budgets?

Cheers, Dimitris

**Comment by DanJonesOcean** [comment]
Hi @menemenlis. I found Ryan's post on Medium about accessing the NASA ECCO Data Portal via Pangeo - I'll give that a try. Thanks for the suggestion!

And I was thinking of the surface CO2 fluxes, as in Figure 4a of the ECCO-Darwin paper you linked to. We're doing some comparison work with another data product in the North Atlantic. 

Best wishes, Dan

**Comment by menemenlis** [comment]
Hi Dustin, would you have available time-integrated surface CO2 flux from the ECCO-Darwin simulation that we can send to Dan?

Thanks, Dimitris

**Comment by DanJonesOcean** [comment]
Thanks for that, @menemenlis. 

I just had a quick look at the ECCO data currently accessible on Pangeo. As far as I can tell, it doesn't look like one can access LLC270 and the ECCO-Darwin data on the NASA ECCO Data Portal via Pangeo at present. 

But a standalone time-integrated surface CO2 flux field would be excellent.

**Comment by menemenlis** [comment]
Hi Dan,

1. Do you want a 2-D field of time-integrated CO2 fluxes?
2. Integrated over what time period? I have January 1992 to December 2020
available. 1992–1995 is the model spin-up period.
3. Are you comfortable using the LLC270 grid?

Best,
Dustin

**Comment by DanJonesOcean** [comment]
1. Yes, please. 
2. Could I get January 2003 - December 2012? 
3. Yes, I'm okay with the LLC270 grid. 

Thanks very much.
